// src/components/AlcoholCalculator/index.tsx
/*
CHECKLIST
move input field to input fields
*/

import { useState, useMemo, useEffect } from 'react';

import InputFields from './organisms/InputFields';
import WelcomeHeader from './organisms/WelcomeHeader';
import ResultSection from './organisms/ResultSection';

import { CurrencyContext } from './contexts/CurrencyContext';

import type { inputtedHistory } from '../../types';

export default function AlcoholCalculator() {
  const [drinkName, setDrinkName] = useState<string>('');
  const [volume, setVolume] = useState<string>('');
  const [abv, setAbv] = useState<string>('');
  const [price, setPrice] = useState<string>('');
  const [currency, setCurrency] = useState('IDR');

  const [isVolumeOnChange, setIsOnVolumeOnChange] = useState<boolean>(false);
  const [isAbvOnChange, setIsOnAbvOnChange] = useState<boolean>(false);
  const [isPriceOnChange, setIsOnPriceOnChange] = useState<boolean>(false);

  // TODO: add different error message for abv > 100 and abv < 1
  const isVolumeInvalid = (isVolumeOnChange && !volume.length) || isNaN(volume);
  const isAbvInvalid = !abv.length || isNaN(abv);
  const isPriceInvalid = !price.length || isNaN(price);
  const isButtonDisabled = isVolumeInvalid || isAbvInvalid || isPriceInvalid || !currency;

  function onSetVolume(value: string) {
    setVolume(value);
    if (!isVolumeOnChange) {
      setIsOnVolumeOnChange(true);
    }
  }

  function onSetAbv(value: string) {
    setAbv(value);
    if (!isAbvOnChange) {
      setIsOnAbvOnChange(true);
    }
  }

  function onSetPrice(value: string) {
    setPrice(value);
    if (!isPriceOnChange) {
      setIsOnPriceOnChange(true);
    }
  }

  // 📜 CODE BLOCK - calculate
  const [history, setHistory] = useState<inputtedHistory[]>([]);
  const [isShowResult, setIsShowResult] = useState(false);

  const isCurrencyDisabled = history.length > 0;

  function calculate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();

    setIsShowResult(true);

    const alcoholVolume = (Number(volume) * Number(abv)) / 100;
    const alcoholPricePerMilliliter = Number(price) / alcoholVolume;
    const alcoholPricePerPercent = (Number(price) / alcoholVolume) * (Number(volume) / 100);

    const newEntry = {
      name: drinkName,
      volume: volume,
      abv: abv,
      price: price,
      currency: currency,
      alcoholVolume: alcoholVolume,
      alcoholPricePerMilliliter: alcoholPricePerMilliliter,
      alcoholPricePerPercent: alcoholPricePerPercent,
    };

    setHistory((prev) => {
      console.log('prev', prev);
      const updated = [...prev, newEntry];
      return updated.length > 2 ? updated.slice(1) : updated;
    });

    setDrinkName('');
    setVolume('');
    setAbv('');
    setPrice('');
    setIsOnVolumeOnChange(false);
    setIsOnAbvOnChange(false);
    setIsOnPriceOnChange(false);
  }

  function onReset() {
    setHistory([]);
    setIsShowResult(false);

    window.scrollTo({
      top: 0,
      behavior: 'smooth', // Optional: Add smooth scrolling effect
    });
  }

  useEffect(() => {
    if (isShowResult) {
      window.scrollTo({
        top: document.body.scrollHeight,
        behavior: 'smooth',
      });
    }
  }, [history]); // runs after history updates and the DOM reflects it

  // 📜 CODE BLOCK - add green text color to the cheaper drink
  const comparisonFlags = useMemo(() => {
    if (history.length === 2) {
      return history.map((item, index) => {
        const otherItem = history[1 - index];

        return {
          isMoreAlcoholVolume: item.alcoholVolume > otherItem.alcoholVolume,
          isAlcoholPricePerMlCheaper:
            item.alcoholPricePerMilliliter < otherItem.alcoholPricePerMilliliter,
          isAlcoholPricePerPercentCheaper:
            item.alcoholPricePerPercent < otherItem.alcoholPricePerPercent,
        };
      });
    }

    return history.map((item) => ({
      isMoreAlcoholVolume: false,
      isAlcoholPricePerMlCheaper: false,
      isAlcoholPricePerPercentCheaper: false,
    }));
  }, [history]);

  // 🖨️ - Render
  return (
    <>
      <div className="flex max-w-screen min-h-screen justify-center items-center flex-col px-4 py-8">
        <WelcomeHeader />

        <form className="flex flex-col max-w-sm w-full" onSubmit={calculate}>
          <InputFields
            drinkName={drinkName}
            setDrinkName={setDrinkName}
            volume={volume}
            onSetVolume={onSetVolume}
            isVolumeInvalid={isVolumeInvalid}
            abv={abv}
            onSetAbv={onSetAbv}
            price={price}
            onSetPrice={onSetPrice}
            currency={currency}
            setCurrency={setCurrency}
            isCurrencyDisabled={isCurrencyDisabled}
          />

          <div className="flex flex-col items-center">
            <p className="text-sm text-center mb-4">
              Alcoholic beverage ain't cheap,
              <br />
              but that doesn't mean you can't efficiently
              <br className="md:hidden" />
              reap what you sip.
            </p>
            <button
              type="submit"
              className="bg-cyan-500 hover:bg-cyan-700 disabled:bg-gray-300 text-white font-bold py-2 px-4 rounded cursor-pointer"
              disabled={isButtonDisabled}
            >
              Calculate the alcohol price! 🧮
            </button>
          </div>
        </form>

        <CurrencyContext.Provider value={currency}>
          <ResultSection
            isShowResult={isShowResult}
            history={history}
            comparisonFlags={comparisonFlags}
            onReset={onReset}
          />
        </CurrencyContext.Provider>
      </div>
    </>
  );
}

// src/components/AlcoholCalculator.vue
<script setup lang="ts">
import { ref, computed, nextTick } from 'vue';

const volume = ref<null | number>(null);
const abv = ref<null | number>(null);
const price = ref<null | number>(null);
const currency = ref<string>('IDR');

const alcoholVolume = ref<number>(0);
const alcoholPricePerMilliliter = ref<number>(0);
const alcoholPricePerPercent = ref<number>(0);

const isShowResult = ref<boolean>(false);

const isButtonDisabled = computed((): boolean => {
  return !volume.value || !abv.value || !price.value || !currency.value;
});

interface History {
  volume: number;
  abv: number;
  price: number;
  currency: string;
  alcoholVolume: number;
  alcoholPricePerMilliliter: string;
  alcoholPricePerPercent: string;
}

const history = ref<History[]>([]);

function currencyFormatter(value: number) {
  return new Intl.NumberFormat(currency.value.toLowerCase() === 'idr' ? 'id' : 'en', {
    maximumFractionDigits: 2,
  }).format(value);
}

async function calculate() {
  isShowResult.value = true;

  const alcoholVolume = (volume.value * abv.value) / 100;
  const alcoholPricePerMilliliter = currencyFormatter(price.value / alcoholVolume);
  const alcoholPricePerPercent = currencyFormatter(
    (price.value / alcoholVolume) * (volume.value / 100),
  );

  if (history.value.length > 1) {
    history.value.shift();
  }

  history.value.push({
    volume: volume.value,
    abv: abv.value,
    price: price.value,
    currency: currency.value,
    alcoholVolume: alcoholVolume,
    alcoholPricePerMilliliter: alcoholPricePerMilliliter,
    alcoholPricePerPercent: alcoholPricePerPercent,
  });

  await nextTick();

  window.scrollTo({
    top: document.body.scrollHeight,
    behavior: 'smooth', // Optional: Add smooth scrolling effect
  });
}
</script>

<template>
  <div
    id="calculator-container"
    class="flex max-w-screen min-h-screen justify-center items-center flex-col px-4 py-8"
  >
    <div class="mb-8 text-center">
      <h1 class="mb-2 text-3xl">Bang for Your Chug!</h1>
      <p class="text-sm">
        Alcoholic beverage ain't cheap,<br />but doesn't mean you can't efficiently reap what you
        sip.
      </p>
    </div>

    <form class="flex flex-col" @submit.prevent="calculate">
      <div class="mb-8 flex flex-col items-center">
        <label for="volume" class="text-xl mb-2">Volume (ml)</label>
        <input
          type="number"
          id="volume"
          name="volume"
          min="0"
          v-model="volume"
          class="border-1 rounded-sm border-gray-300 px-3 py-2 text-center"
        />
      </div>

      <div class="mb-8 flex flex-col items-center">
        <label for="alcohol" class="text-xl mb-2">Alcohol by Volume (%)</label>
        <input
          type="number"
          id="alcohol"
          name="alcohol"
          min="0"
          step=".1"
          v-model="abv"
          class="border-1 rounded-sm border-gray-300 px-3 py-2 text-center"
        />
      </div>

      <div class="mb-8 flex flex-col items-center">
        <label for="price" class="text-xl mb-2">Price</label>
        <input
          type="number"
          id="price"
          name="price"
          min="0"
          v-model="price"
          class="border-1 rounded-sm border-gray-300 px-3 py-2 text-center"
        />
      </div>

      <div class="mb-12 flex flex-col items-center">
        <label for="price" class="text-xl mb-2">Currency</label>
        <input
          type="text"
          id="price"
          name="price"
          v-model="currency"
          class="border-1 rounded-sm border-gray-300 px-3 py-2 text-center"
        />
      </div>

      <div class="flex flex-col items-center">
        <button
          type="submit"
          class="bg-cyan-500 hover:bg-cyan-700 disabled:bg-gray-300 text-white font-bold py-2 px-4 rounded cursor-pointer"
          :disabled="isButtonDisabled"
          @submit.prevent="calculate"
        >
          Calculate the alcohol price!
        </button>
      </div>
    </form>

    <div v-if="isShowResult">
      <hr class="w-md pb-8 mt-8 mx-auto" />
      <div class="flex flex-row gap-12 justify-center items-center">
        <template v-for="(item, index) in history">
          <div class="text-center">
            <p class="font-semibold text-sm mb-4">{{ index === 0 ? 'Prev' : 'New' }}</p>
            <p>Total alcohol:</p>
            <p class="mb-6 text-xl font-semibold">{{ item.alcoholVolume }}ml</p>
            <p>Alcohol price:</p>
            <p class="text-xl">
              <span class="font-semibold"
                >{{ item.alcoholPricePerMilliliter }} {{ item.currency }}</span
              >
              per <span class="font-semibold">ml</span>
            </p>
            <p class="text-xl mb-12">
              <span class="font-semibold"
                >{{ item.alcoholPricePerPercent }} {{ item.currency }}</span
              >
              per <span class="font-semibold">1% ({{ item.volume / 100 }}ml)</span>
            </p>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>
